FROM php:8.3-fpm

# Potrzebne zależności
RUN apt-get update && apt-get install -y \
    libzip-dev zip unzip curl git \
    && docker-php-ext-install pdo_mysql sockets

# Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# Skopiuj aplikację
WORKDIR /var/www/html
COPY . .

# Laravel: instalacja
RUN composer install --no-dev --optimize-autoloader \
    && php artisan config:cache \
    && php artisan route:cache \
    && php artisan view:cache

#CMD ["php-fpm"]
