version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    working_dir: /var/www/html
    environment:
      APP_ENV: production
    command: sh -c "php-fpm"
    volumes:
      - .:/var/www/html # Możesz usunąć ten volume później, jak skopiujesz kod do obrazu!
    depends_on:
      - mysql

  node:
    image: node:18
    container_name: vite
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: sh -c "npm ci && npm run build"
    profiles: ["build"]

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - .:/var/www/html
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app

volumes:
  mysql_data:
  caddy_data:
  caddy_config:
