version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    ports:
      - "8000:8000"
    command: php artisan serve --host=0.0.0.0 --port=8000
    user: "${UID}:${GID}"

  node:
     image: node:18
     container_name: vite
     restart: unless-stopped
     working_dir: /var/www/html
     volumes:
         - ./:/var/www/html
     ports:
         - "5173:5173"
     command: sh -c "npm install && npm run dev"
#     command: sh -c "while true; do sleep 60; done"
     depends_on:
         - app

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
